// <auto-generated />
namespace TPGestionTournoiJeuVideo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class FirstM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstM));
        
        string IMigrationMetadata.Id
        {
            get { return "201911290020373_FirstM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
